baseURL = 'https://passkeys.dev/'
languageCode = 'en-us'
title = 'passkeys.dev'

enableGitInfo = true
enableRobotsTXT = true

[build]
  writeStats = true

[[module.imports]]
  path = 'github.com/gethinode/hinode'

[markup]
  [markup.highlight]
    style = 'onedark'
